version: 2
updates:
  # npmパッケージの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # 週に１回更新をチェックする

    # 特定の更新タイプを無視する設定
    # メジャーアップデートを無効化（破壊的変更の可能性があるため）
    ignore:
      # すべての依存関係に対して
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # 複数のプルリクを１つにまとめる設定
    # マイナーおよびパッチ更新をまとめる
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
